In [1]:
import pandas as pd, scipy.stats as st
import numpy as np
import matplotlib.pyplot as plt

In [5]:
data =  pd.ExcelFile("/Users/uliakaliberda/Downloads/LabsMS/Lab5.xls")
df = data.parse("1")
first = pd.DataFrame()
first["A"] = df["X1"]
first["B"] = df["X2"]
first["C"] = first["A"] - first["B"]
first[:10]

           A          B         C
0  10.234236   9.628931  0.605305
1   7.030718   9.731835 -2.701117
2  12.820179  10.118719  2.701461
3  12.520119  10.068633  2.451486
4  10.083483   9.889096  0.194386
5   7.372015   9.954325 -2.582310
6   8.977075   7.542272  1.434803
7  10.303096  10.808591 -0.505495
8   9.931520   8.130056  1.801463
9   7.120713  10.144632 -3.023920

Criteria V-M

In [10]:
first["D"] = sorted(abs(first["C"]))
first

            A          B         C         D
0   10.234236   9.628931  0.605305  0.005411
1    7.030718   9.731835 -2.701117  0.194386
2   12.820179  10.118719  2.701461  0.387240
3   12.520119  10.068633  2.451486  0.452719
4   10.083483   9.889096  0.194386  0.489058
5    7.372015   9.954325 -2.582310  0.505495
6    8.977075   7.542272  1.434803  0.527368
7   10.303096  10.808591 -0.505495  0.605305
8    9.931520   8.130056  1.801463  0.698092
9    7.120713  10.144632 -3.023920  1.078542
10   9.324191   7.183536  2.140655  1.235262
11   9.145703   7.236964  1.908738  1.243520
12   9.150393   7.669129  1.481264  1.270239
13  11.808526   8.941162  2.867364  1.314606
14  12.099769   6.994775  5.104994  1.367916
15   4.566460  12.126235 -7.559775  1.378376
16   8.136445  11.328640 -3.192195  1.434803
17   7.384298   8.082390 -0.698092  1.475034
18  10.542134  10.014766  0.527368  1.481264
19   5.737817  10.264149 -4.526332  1.506746
20   8.242470   8.237058  0.005411  1.771987
21   8.719998  10.510772 -1.790775  1.790775
22   9.385116  12.254142 -2.869026  1.801463
23   8.411172  10.736222 -2.325050  1.861172
24   7.310561  11.633059 -4.322499  1.908738
25  14.790782  11.632634  3.158148  2.082893
26   8.304647   9.383190 -1.078542  2.140655
27  11.887784  10.381037  1.506746  2.230272
28  11.188746   9.918507  1.270239  2.325050
29  10.461132  10.913851 -0.452719  2.451486
30   7.390041  10.575383 -3.185341  2.461188
31   9.651320  13.600253 -3.948933  2.582310
32  12.256743  11.767685  0.489058  2.596362
33  11.313228  12.681145 -1.367916  2.701117
34   9.848310   8.076323  1.771987  2.701461
35  13.955174  11.724902  2.230272  2.857278
36  11.268008  13.129180 -1.861172  2.867364
37   7.768809   6.390434  1.378376  2.869026
38  12.163761  11.776521  0.387240  3.023920
39  10.443551   7.586274  2.857278  3.158148
40   8.383541   9.627062 -1.243520  3.185341
41  11.804383   9.721490  2.082893  3.192195
42   9.627062   8.391800  1.235262  3.640071
43   8.738531  12.378601 -3.640071  3.770183
44   9.360527  10.835562 -1.475034  3.948933
45  11.651492   9.055131  2.596362  4.209733
46  12.521474  11.206868  1.314606  4.322499
47   7.852647  11.622830 -3.770183  4.526332
48   9.222027  13.431760 -4.209733  5.104994
49  10.729842   8.268654  2.461188  7.559775

In [11]:
signs = []
for elemd in first["D"]:
    for i in range(len(first["C"])):
        if abs(first["C"][i])==elemd:
            if (first["C"][i])>0:
                    signs.append(1)
            else:
                    signs.append(-1)
first["E"] = signs

In [13]:
U = 0; #ranks
for i in range(len(first["E"])):
    if first["E"][i]>0:
        U+=i;
U

550

In [35]:
M = 51*50/2
D = M*51/12
D

5418.75

In [36]:
T = (U-M)*D**(-0.5)
T

-9.848916356764205

In [38]:
F = (1/2*np.pi)*(np.exp(-0.5))
F

0.9527361323650899

In [ ]:
if F>T:
    print("H0")
else:
    print("H1")